# Generated by Django 2.1 on 2018-08-21 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenCarro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.PositiveIntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionario.Marca')),
            ],
        ),
        migrations.AddField(
            model_name='almacencarro',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionario.Color'),
        ),
        migrations.AddField(
            model_name='almacencarro',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionario.Marca'),
        ),
        migrations.AddField(
            model_name='almacencarro',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionario.Modelo'),
        ),
    ]
